Repository Yubico/Yubico.NET.SDK, pull requests merged in 2024-06, with the labels that each got.

#103 Adding support for deleting and moving keys between slots
  .editorconfig
  Yubico.YubiKey/src/Resources/ExceptionMessages.Designer.cs
  Yubico.YubiKey/src/Resources/ExceptionMessages.resx
  Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/DeleteKeyCommand.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/DeleteKeyResponse.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/MoveKeyCommand.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/MoveKeyResponse.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Piv/PivSession.cs
  Yubico.YubiKey/src/Yubico/YubiKey/YubiKeyFeature.cs
  Yubico.YubiKey/src/Yubico/YubiKey/YubiKeyFeatureExtensions.cs
  Yubico.YubiKey/tests/integration/Yubico/YubiKey/Piv/GenerateTests.cs
  Yubico.YubiKey/tests/integration/Yubico/YubiKey/Piv/MoveDeleteKeyTests.cs
  Yubico.YubiKey/tests/integration/Yubico/YubiKey/Piv/SignTests.cs
  Yubico.YubiKey/tests/utilities/Yubico/YubiKey/TestUtilities/SampleKeyPairs.cs
Labels: documentation, enhancement

#105 Fix: Update ManagementKeyAlgorithm on PIV Application reset
  .editorconfig
  Yubico.YubiKey/src/Yubico/YubiKey/Piv/PivSession.Pinonly.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Piv/PivSession.cs
  Yubico.YubiKey/tests/integration/Yubico/YubiKey/Piv/ManagementKeyTests.cs
Labels: bug

#107 Fix: Add dotnet to path for failing verify-code-style GitHub Action
  .github/workflows/verify-code-style.yml
  Yubico.NET.SDK.sln
Labels: bug

#111 Update dependency: xUnit
  Yubico.Core/tests/Yubico.Core.UnitTests.csproj
  Yubico.YubiKey/tests/integration/Yubico.YubiKey.IntegrationTests.csproj
  Yubico.YubiKey/tests/unit/Yubico.YubiKey.UnitTests.csproj
Labels: enhancement

#108 Add PIV Bio extensions
  Yubico.YubiKey/docs/users-manual/application-piv/apdu/bio-metadata.md
  Yubico.YubiKey/docs/users-manual/application-piv/apdu/verify-temporary-pin.md
  Yubico.YubiKey/docs/users-manual/application-piv/apdu/verify-uv.md
  Yubico.YubiKey/docs/users-manual/application-piv/commands.md
  Yubico.YubiKey/src/Resources/ExceptionMessages.Designer.cs
  Yubico.YubiKey/src/Resources/ExceptionMessages.resx
  Yubico.YubiKey/src/Resources/ResponseStatusMessages.Designer.cs
  Yubico.YubiKey/src/Resources/ResponseStatusMessages.resx
  Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/GetBioMetadataCommand.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/GetBioMetadataResponse.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/VerifyTemporaryPinCommand.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/VerifyTemporaryPinResponse.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/VerifyUvCommand.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/VerifyUvResponse.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Piv/PivBioMetadata.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Piv/PivPinPolicy.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Piv/PivSession.cs
  Yubico.YubiKey/tests/integration/Yubico/YubiKey/Piv/BioMultiProtocolTests.cs
Labels: enhancement

#110 Add device reset command
  Yubico.Core/tests/Yubico.Core.UnitTests.csproj
  Yubico.Core/tests/Yubico/Core/Cryptography/AesGcmPrimitivesOpenSslTests.cs
  Yubico.YubiKey/src/Yubico/YubiKey/IYubiKeyDevice.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Management/Commands/DeviceResetCommand.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Management/Commands/DeviceResetResponse.cs
  Yubico.YubiKey/src/Yubico/YubiKey/YubiKeyDevice.Instance.cs
  Yubico.YubiKey/src/Yubico/YubiKey/YubiKeyFeature.cs
  Yubico.YubiKey/src/Yubico/YubiKey/YubiKeyFeatureExtensions.cs
  Yubico.YubiKey/tests/utilities/Yubico/YubiKey/TestUtilities/HollowYubiKeyDevice.cs
Labels: enhancement

#112 Additions for PIN complexity violation
  .editorconfig
  Yubico.YubiKey/docs/users-manual/sdk-programming-guide/pin-complexity-policy.md
  Yubico.YubiKey/docs/users-manual/toc.yml
  Yubico.YubiKey/examples/Fido2SampleCode/KeyCollector/Fido2SampleKeyCollector.cs
  Yubico.YubiKey/examples/PivSampleCode/KeyCollector/SampleKeyCollector.cs
  Yubico.YubiKey/src/Resources/ExceptionMessages.Designer.cs
  Yubico.YubiKey/src/Resources/ExceptionMessages.resx
  Yubico.YubiKey/src/Resources/ResponseStatusMessages.Designer.cs
  Yubico.YubiKey/src/Resources/ResponseStatusMessages.resx
  Yubico.YubiKey/src/Yubico/YubiKey/Fido2/Commands/Fido2Response.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Fido2/Fido2Exception.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Fido2/Fido2Session.Pin.cs
  Yubico.YubiKey/src/Yubico/YubiKey/KeyEntryData.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/ChangeReferenceDataResponse.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/ResetRetryResponse.cs
  Yubico.YubiKey/src/Yubico/YubiKey/Piv/PivSession.Pin.cs
  Yubico.YubiKey/tests/integration/Yubico/YubiKey/PinComplexityTests.cs
Labels: documentation, enhancement
